### ISSUE TITLE
Project not updated in last 8 month

### ISSUE THREAD

**Issue by Moanrisy** [brandelune/brandelune.github.io#3]
> Nobody but me is reading this readme file, so let me wish myself good luck :)

I read your readme file :), Hope you keep update your story again soon.
Your project inspire me to make my own, thanks.

**Comment by brandelune** [comment]
Thank you !!! :) I'm hoping I'll be able to resume soon :)

**Comment by brandelune** [comment]
I've been kind of updating the whole thing, starting with the emacs lisp templating system. Thank you for the nudge.
